let gameData = {
    gems: 100,
    streak: 0,
    lastDate: "",
    lastWeek: "",
    lastMonth: "",
    taskStatuses: {},
    dailyChestCollected: false,
    parentCode: "1234",
    windowCount: 0,
    petName: "Мурка",
    lastNameChange: null,
    parentModeActive: false,
    purchasedAccessories: [],
    purchasedFurniture: [],
    purchasedDecor: [],
    purchasedSmart: [],
    activeRight: null,
    activeLeft: null,
    activeTop: null,
    currentLevel: 0,
    dailyBonusClaimed: false,
    lastBonusDay: "",
    lastWeekLevelUp: 0,
    pet: {
        hunger: 20,
        happiness: 50,
        energy: 70,
        clean: 80,
        lastUpdateTime: Date.now(),
        petCount: 0,
        playCount: 0,
        playBallCount: 0,
        playLaserCount: 0,
        playCandyCount: 0,
        batheCount: 0,
        milkCount: 0,
        brushCount: 0,
        giftCount: 0,
        sleepCount: 0,
        feedCount: 0,
        litterCount: 0,
        currentAccessory: null,
        sickUntil: null,
        sleepUntil: null,
        lastPetTime: 0,
        lastCleaned: Date.now(),
        needsLitter: 0,
        litterWarningSent: false,
        feedLastTime: 0,
        milkLastTime: 0,
        sleepLastTime: 0,
        petLastTime: 0,
        playLastTime: 0,
        playBallLastTime: 0,
        playLaserLastTime: 0,
        playCandyLastTime: 0,
        brushLastTime: 0,
        batheLastTime: 0,
        giftLastTime: 0,
        litterLastTime: 0
    },
    style: 0,
    smartStat: 0,
    cozy: 0,
    beauty: 0,
    notificationsEnabled: false
};

let currentFilter = "daily";
let audioCtx = null;
let confettiActive = false;
let hungerNotifSent = false;
let isInitialized = false;